import { sql } from 'drizzle-orm';
import {
  bigint, check, foreignKey, index, integer, jsonb, pgTable, primaryKey,
  text, timestamp, unique, uniqueIndex, uuid,
} from 'drizzle-orm/pg-core';
import { products } from './catalog';
import { operations } from './operations';
import { students } from './students';
import { taskAssignments, tasks } from './tasks';

export const transactionKinds = [
  'CHECKOUT', 'CANCELLATION', 'ADMIN_ADJUSTMENT', 'TASK_REWARD', 'LEGACY',
] as const;
export const adjustmentModes = ['add', 'subtract', 'set'] as const;
export const inventoryReasons = ['CHECKOUT', 'CANCELLATION', 'ADMIN_ADJUSTMENT', 'LEGACY_IMPORT'] as const;
export const taskCompletionStatuses = ['COMPLETED', 'CANCELLED'] as const;
export const taskCompletionSources = ['BANK', 'ADMIN', 'CARRY_FORWARD', 'ADMIN_RESET'] as const;

export const transactions = pgTable('transactions', {
  tenantId: uuid('tenant_id').notNull(),
  transactionId: text('transaction_id').notNull(),
  eventSequence: bigint('event_sequence', { mode: 'bigint' }).generatedByDefaultAsIdentity().notNull(),
  occurredAt: timestamp('occurred_at', { withTimezone: true }).notNull(),
  studentId: text('student_id').notNull(),
  studentNameSnapshot: text('student_name_snapshot').notNull(),
  kind: text('kind').$type<(typeof transactionKinds)[number]>().notNull(),
  legacyTotalAmount: bigint('legacy_total_amount', { mode: 'bigint' }).notNull(),
  balanceDelta: bigint('balance_delta', { mode: 'bigint' }).notNull(),
  balanceBefore: bigint('balance_before', { mode: 'bigint' }).notNull(),
  balanceAfter: bigint('balance_after', { mode: 'bigint' }).notNull(),
  operatorSnapshot: text('operator_snapshot').notNull(),
  legacyStatusSnapshot: text('legacy_status_snapshot'),
  reversesTransactionId: text('reverses_transaction_id'),
  operationId: text('operation_id'),
  operationHash: text('operation_hash'),
  schemaVersion: integer('schema_version').default(1).notNull(),
  createdAt: timestamp('created_at', { withTimezone: true }).defaultNow().notNull(),
}, (table) => [
  primaryKey({ name: 'transactions_pkey', columns: [table.tenantId, table.transactionId] }),
  unique('transactions_event_sequence_unique').on(table.tenantId, table.eventSequence),
  foreignKey({ name: 'transactions_student_fk', columns: [table.tenantId, table.studentId], foreignColumns: [students.tenantId, students.studentId] }),
  foreignKey({ name: 'transactions_reversal_fk', columns: [table.tenantId, table.reversesTransactionId], foreignColumns: [table.tenantId, table.transactionId] }),
  index('transactions_student_history_idx').on(table.tenantId, table.studentId, table.occurredAt.desc(), table.eventSequence.desc()),
  uniqueIndex('transactions_operation_unique').on(table.tenantId, table.operationId).where(sql`${table.operationId} IS NOT NULL`),
  check('transactions_kind_check', sql`${table.kind} IN ('CHECKOUT', 'CANCELLATION', 'ADMIN_ADJUSTMENT', 'TASK_REWARD', 'LEGACY')`),
  check('transactions_id_check', sql`${table.transactionId} = btrim(${table.transactionId}) AND length(${table.transactionId}) > 0`),
  check('transactions_reversal_id_check', sql`${table.reversesTransactionId} IS NULL OR (${table.reversesTransactionId} = btrim(${table.reversesTransactionId}) AND length(${table.reversesTransactionId}) > 0)`),
  check('transactions_not_self_reversal_check', sql`${table.reversesTransactionId} IS NULL OR ${table.reversesTransactionId} <> ${table.transactionId}`),
  check('transactions_operation_id_check', sql`${table.operationId} IS NULL OR (${table.operationId} = btrim(${table.operationId}) AND length(${table.operationId}) > 0)`),
  check('transactions_safe_money_check', sql`${table.legacyTotalAmount} BETWEEN -9007199254740991 AND 9007199254740991 AND ${table.balanceDelta} BETWEEN -9007199254740991 AND 9007199254740991 AND ${table.balanceBefore} BETWEEN -9007199254740991 AND 9007199254740991 AND ${table.balanceAfter} BETWEEN -9007199254740991 AND 9007199254740991`),
  check('transactions_balance_delta_check', sql`${table.balanceAfter} - ${table.balanceBefore} = ${table.balanceDelta}`),
  check('transactions_reversal_shape_check', sql`(${table.kind} = 'CANCELLATION' AND ${table.reversesTransactionId} IS NOT NULL) OR (${table.kind} <> 'CANCELLATION' AND ${table.reversesTransactionId} IS NULL)`),
  check('transactions_operation_pair_check', sql`(${table.operationId} IS NULL) = (${table.operationHash} IS NULL)`),
  check('transactions_operation_hash_check', sql`${table.operationHash} IS NULL OR length(btrim(${table.operationHash})) > 0`),
  check('transactions_schema_version_check', sql`${table.schemaVersion} >= 1`),
]);

export const transactionItems = pgTable('transaction_items', {
  tenantId: uuid('tenant_id').notNull(),
  itemId: uuid('item_id').defaultRandom().notNull(),
  transactionId: text('transaction_id').notNull(),
  lineNumber: integer('line_number').default(1).notNull(),
  productIdSnapshot: text('product_id_snapshot').notNull(),
  currentProductId: text('current_product_id'),
  productNameSnapshot: text('product_name_snapshot').notNull(),
  quantity: bigint('quantity', { mode: 'bigint' }).notNull(),
  unitPriceSnapshot: bigint('unit_price_snapshot', { mode: 'bigint' }).notNull(),
  subtotalSnapshot: bigint('subtotal_snapshot', { mode: 'bigint' }).notNull(),
  regularUnitPrice: bigint('regular_unit_price', { mode: 'bigint' }),
  regularTotal: bigint('regular_total', { mode: 'bigint' }),
  totalQuantity: bigint('total_quantity', { mode: 'bigint' }),
  paidQuantity: bigint('paid_quantity', { mode: 'bigint' }),
  freeQuantity: bigint('free_quantity', { mode: 'bigint' }),
  finalTotal: bigint('final_total', { mode: 'bigint' }),
  totalDiscount: bigint('total_discount', { mode: 'bigint' }),
  adjustmentsSnapshot: jsonb('adjustments_snapshot').$type<unknown[]>(),
  appliedPromotionsSnapshot: jsonb('applied_promotions_snapshot').$type<unknown[]>(),
  createdAt: timestamp('created_at', { withTimezone: true }).defaultNow().notNull(),
}, (table) => [
  primaryKey({ name: 'transaction_items_pkey', columns: [table.tenantId, table.itemId] }),
  unique('transaction_items_transaction_line_unique').on(table.tenantId, table.transactionId, table.lineNumber),
  foreignKey({ name: 'transaction_items_transaction_fk', columns: [table.tenantId, table.transactionId], foreignColumns: [transactions.tenantId, transactions.transactionId] }),
  foreignKey({ name: 'transaction_items_current_product_fk', columns: [table.tenantId, table.currentProductId], foreignColumns: [products.tenantId, products.productId] }),
  check('transaction_items_product_snapshot_check', sql`${table.productIdSnapshot} = btrim(${table.productIdSnapshot}) AND length(${table.productIdSnapshot}) > 0`),
  check('transaction_items_base_check', sql`${table.quantity} BETWEEN 1 AND 9007199254740991 AND ${table.unitPriceSnapshot} BETWEEN -9007199254740991 AND 9007199254740991 AND ${table.subtotalSnapshot} BETWEEN -9007199254740991 AND 9007199254740991`),
  check('transaction_items_extended_shape_check', sql`num_nonnulls(${table.regularUnitPrice}, ${table.regularTotal}, ${table.totalQuantity}, ${table.paidQuantity}, ${table.freeQuantity}, ${table.finalTotal}, ${table.totalDiscount}, ${table.adjustmentsSnapshot}, ${table.appliedPromotionsSnapshot}) IN (0, 9)`),
  check('transaction_items_extended_values_check', sql`${table.totalQuantity} IS NULL OR (${table.regularUnitPrice} BETWEEN 0 AND 9007199254740991 AND ${table.regularTotal} BETWEEN 0 AND 9007199254740991 AND ${table.totalQuantity} BETWEEN 1 AND 9007199254740991 AND ${table.paidQuantity} BETWEEN 0 AND 9007199254740991 AND ${table.freeQuantity} BETWEEN 0 AND 9007199254740991 AND ${table.finalTotal} BETWEEN 0 AND 9007199254740991 AND ${table.totalDiscount} BETWEEN 0 AND 9007199254740991 AND ${table.paidQuantity} + ${table.freeQuantity} = ${table.totalQuantity} AND jsonb_typeof(${table.adjustmentsSnapshot}) = 'array' AND jsonb_typeof(${table.appliedPromotionsSnapshot}) = 'array')`),
]);

export const adjustments = pgTable('adjustments', {
  tenantId: uuid('tenant_id').notNull(),
  adjustmentId: text('adjustment_id').notNull(),
  transactionId: text('transaction_id').notNull(),
  mode: text('mode').$type<(typeof adjustmentModes)[number]>().notNull(),
  requestedAmount: bigint('requested_amount', { mode: 'bigint' }).notNull(),
  operatorSnapshot: text('operator_snapshot').notNull(),
  legacyAdjustmentId: text('legacy_adjustment_id'),
  createdAt: timestamp('created_at', { withTimezone: true }).defaultNow().notNull(),
}, (table) => [
  primaryKey({ name: 'adjustments_pkey', columns: [table.tenantId, table.adjustmentId] }),
  unique('adjustments_transaction_unique').on(table.tenantId, table.transactionId),
  foreignKey({ name: 'adjustments_transaction_fk', columns: [table.tenantId, table.transactionId], foreignColumns: [transactions.tenantId, transactions.transactionId] }),
  check('adjustments_mode_check', sql`${table.mode} IN ('add', 'subtract', 'set')`),
  check('adjustments_id_check', sql`${table.adjustmentId} = btrim(${table.adjustmentId}) AND length(${table.adjustmentId}) > 0`),
  check('adjustments_amount_safe_check', sql`${table.requestedAmount} BETWEEN -9007199254740991 AND 9007199254740991`),
]);

export const inventoryLedger = pgTable('inventory_ledger', {
  tenantId: uuid('tenant_id').notNull(),
  inventoryEventId: uuid('inventory_event_id').defaultRandom().notNull(),
  eventSequence: bigint('event_sequence', { mode: 'bigint' }).generatedByDefaultAsIdentity().notNull(),
  productId: text('product_id').notNull(),
  transactionId: text('transaction_id'),
  quantityDelta: bigint('quantity_delta', { mode: 'bigint' }).notNull(),
  stockBefore: bigint('stock_before', { mode: 'bigint' }).notNull(),
  stockAfter: bigint('stock_after', { mode: 'bigint' }).notNull(),
  reason: text('reason').$type<(typeof inventoryReasons)[number]>().notNull(),
  operationId: text('operation_id'),
  operationHash: text('operation_hash'),
  occurredAt: timestamp('occurred_at', { withTimezone: true }).notNull(),
  createdAt: timestamp('created_at', { withTimezone: true }).defaultNow().notNull(),
}, (table) => [
  primaryKey({ name: 'inventory_ledger_pkey', columns: [table.tenantId, table.inventoryEventId] }),
  unique('inventory_ledger_event_sequence_unique').on(table.tenantId, table.eventSequence),
  foreignKey({ name: 'inventory_ledger_product_fk', columns: [table.tenantId, table.productId], foreignColumns: [products.tenantId, products.productId] }),
  foreignKey({ name: 'inventory_ledger_transaction_fk', columns: [table.tenantId, table.transactionId], foreignColumns: [transactions.tenantId, transactions.transactionId] }),
  index('inventory_ledger_product_event_idx').on(table.tenantId, table.productId, table.eventSequence),
  uniqueIndex('inventory_ledger_operation_unique').on(table.tenantId, table.operationId).where(sql`${table.operationId} IS NOT NULL`),
  check('inventory_ledger_stock_check', sql`${table.quantityDelta} BETWEEN -9007199254740991 AND 9007199254740991 AND ${table.stockBefore} BETWEEN 0 AND 9007199254740991 AND ${table.stockAfter} BETWEEN 0 AND 9007199254740991 AND ${table.stockAfter} - ${table.stockBefore} = ${table.quantityDelta}`),
  check('inventory_ledger_reason_check', sql`${table.reason} IN ('CHECKOUT', 'CANCELLATION', 'ADMIN_ADJUSTMENT', 'LEGACY_IMPORT')`),
  check('inventory_ledger_operation_id_check', sql`${table.operationId} IS NULL OR (${table.operationId} = btrim(${table.operationId}) AND length(${table.operationId}) > 0)`),
  check('inventory_ledger_operation_pair_check', sql`(${table.operationId} IS NULL) = (${table.operationHash} IS NULL)`),
  check('inventory_ledger_operation_hash_check', sql`${table.operationHash} IS NULL OR length(btrim(${table.operationHash})) > 0`),
]);

export const taskCompletions = pgTable('task_completions', {
  tenantId: uuid('tenant_id').notNull(),
  completionId: text('completion_id').notNull(),
  eventSequence: bigint('event_sequence', { mode: 'bigint' }).generatedByDefaultAsIdentity().notNull(),
  completedAt: timestamp('completed_at', { withTimezone: true }).notNull(),
  taskInstanceId: text('task_instance_id'),
  taskIdSnapshot: text('task_id_snapshot').notNull(),
  taskNameSnapshot: text('task_name_snapshot').notNull(),
  studentId: text('student_id').notNull(),
  studentNameSnapshot: text('student_name_snapshot').notNull(),
  rewardSnapshot: bigint('reward_snapshot', { mode: 'bigint' }).notNull(),
  balanceBefore: bigint('balance_before', { mode: 'bigint' }).notNull(),
  balanceAfter: bigint('balance_after', { mode: 'bigint' }).notNull(),
  status: text('status').notNull(),
  note: text('note'),
  cycleId: text('cycle_id'),
  cycleStartAt: timestamp('cycle_start_at', { withTimezone: true }),
  cycleEndAt: timestamp('cycle_end_at', { withTimezone: true }),
  ruleVersion: integer('rule_version'),
  timezone: text('timezone'),
  source: text('source').$type<(typeof taskCompletionSources)[number]>(),
  assignmentId: text('assignment_id'),
  transactionId: text('transaction_id'),
  operationId: text('operation_id'),
  operationHash: text('operation_hash'),
  adminOperationId: text('admin_operation_id'),
  adminOperationHash: text('admin_operation_hash'),
  schemaVersion: integer('schema_version').default(1).notNull(),
  evidenceProvider: text('evidence_provider'),
  evidenceBoardId: text('evidence_board_id'),
  evidencePostId: text('evidence_post_id'),
  evidenceCreatedAt: timestamp('evidence_created_at', { withTimezone: true }),
  evidenceAuthorFullName: text('evidence_author_full_name'),
  createdAt: timestamp('created_at', { withTimezone: true }).defaultNow().notNull(),
}, (table) => [
  primaryKey({ name: 'task_completions_pkey', columns: [table.tenantId, table.completionId] }),
  unique('task_completions_event_sequence_unique').on(table.tenantId, table.eventSequence),
  foreignKey({ name: 'task_completions_task_fk', columns: [table.tenantId, table.taskInstanceId], foreignColumns: [tasks.tenantId, tasks.taskInstanceId] }),
  foreignKey({ name: 'task_completions_student_fk', columns: [table.tenantId, table.studentId], foreignColumns: [students.tenantId, students.studentId] }),
  foreignKey({ name: 'task_completions_assignment_fk', columns: [table.tenantId, table.assignmentId], foreignColumns: [taskAssignments.tenantId, taskAssignments.assignmentId] }),
  foreignKey({ name: 'task_completions_transaction_fk', columns: [table.tenantId, table.transactionId], foreignColumns: [transactions.tenantId, transactions.transactionId] }),
  foreignKey({ name: 'task_completions_admin_operation_fk', columns: [table.tenantId, table.adminOperationId], foreignColumns: [operations.tenantId, operations.operationId] }),
  index('task_completions_cycle_student_event_idx').on(table.tenantId, table.taskInstanceId, table.cycleId, table.studentId, table.eventSequence),
  uniqueIndex('task_completions_operation_unique').on(table.tenantId, table.operationId).where(sql`${table.operationId} IS NOT NULL`),
  check('task_completions_id_check', sql`${table.completionId} = btrim(${table.completionId}) AND length(${table.completionId}) > 0`),
  check('task_completions_task_id_snapshot_check', sql`${table.taskIdSnapshot} = btrim(${table.taskIdSnapshot}) AND length(${table.taskIdSnapshot}) > 0`),
  check('task_completions_status_check', sql`length(btrim(${table.status})) > 0`),
  check('task_completions_source_check', sql`${table.source} IS NULL OR ${table.source} IN ('BANK', 'ADMIN', 'CARRY_FORWARD', 'ADMIN_RESET')`),
  check('task_completions_reward_check', sql`${table.rewardSnapshot} BETWEEN 0 AND 9007199254740991`),
  check('task_completions_balances_check', sql`${table.balanceBefore} BETWEEN -9007199254740991 AND 9007199254740991 AND ${table.balanceAfter} BETWEEN -9007199254740991 AND 9007199254740991`),
  check('task_completions_carry_forward_check', sql`${table.source} IS DISTINCT FROM 'CARRY_FORWARD' OR ${table.rewardSnapshot} = 0`),
  check('task_completions_cycle_metadata_check', sql`num_nonnulls(${table.taskInstanceId}, ${table.cycleId}, ${table.cycleStartAt}, ${table.ruleVersion}, ${table.timezone}, ${table.source}) IN (0, 6)`),
  check('task_completions_cycle_window_check', sql`${table.cycleEndAt} IS NULL OR (${table.cycleStartAt} IS NOT NULL AND ${table.cycleEndAt} > ${table.cycleStartAt})`),
  check('task_completions_rule_version_check', sql`${table.ruleVersion} IS NULL OR ${table.ruleVersion} >= 1`),
  check('task_completions_timezone_check', sql`${table.timezone} IS NULL OR ${table.timezone} = 'Asia/Seoul'`),
  check('task_completions_operation_id_check', sql`${table.operationId} IS NULL OR (${table.operationId} = btrim(${table.operationId}) AND length(${table.operationId}) > 0)`),
  check('task_completions_operation_pair_check', sql`(${table.operationId} IS NULL) = (${table.operationHash} IS NULL)`),
  check('task_completions_operation_hash_check', sql`${table.operationHash} IS NULL OR length(btrim(${table.operationHash})) > 0`),
  check('task_completions_admin_operation_pair_check', sql`(${table.adminOperationId} IS NULL) = (${table.adminOperationHash} IS NULL)`),
  check('task_completions_admin_operation_id_check', sql`${table.adminOperationId} IS NULL OR (${table.adminOperationId} = btrim(${table.adminOperationId}) AND length(${table.adminOperationId}) > 0)`),
  check('task_completions_admin_operation_hash_check', sql`${table.adminOperationHash} IS NULL OR ${table.adminOperationHash} ~ '^[0-9a-f]{64}$'`),
  check('task_completions_schema_version_check', sql`${table.schemaVersion} >= 1`),
  check('task_completions_evidence_check', sql`num_nonnulls(${table.evidenceProvider}, ${table.evidenceBoardId}, ${table.evidencePostId}, ${table.evidenceCreatedAt}, ${table.evidenceAuthorFullName}) = 0 OR (num_nonnulls(${table.evidenceProvider}, ${table.evidenceBoardId}, ${table.evidencePostId}, ${table.evidenceCreatedAt}, ${table.evidenceAuthorFullName}) = 5 AND ${table.evidenceProvider} = 'PADLET' AND length(btrim(${table.evidenceBoardId})) > 0 AND length(btrim(${table.evidencePostId})) > 0 AND length(btrim(${table.evidenceAuthorFullName})) > 0)`),
]);
